/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PDC_Project1;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alex 20125029
 */

public class GUI extends java.awt.Frame
{

    public CardLayout cards;
    public ArrayList<JButton> qButtons;
    public Game thisGame;
    public ArrayList<JButton> btnLifelines;
    
    /**
     * Creates new form GUI
     */
    public GUI()
    {
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension screenSize = kit.getScreenSize();
        int screenWidth = screenSize.width;
        int screenHeight = screenSize.height;
        int windowHeight = screenHeight/2;
        int windowWidth = screenWidth/2;
        
        this.setTitle("Who Wants to be a Millionaire!");
        this.setLocation(windowWidth/2,windowHeight/2);
        this.setResizable(false);
        
        initComponents();
        cards = (CardLayout) CardHolder.getLayout();
        qButtons = new ArrayList<JButton>();
        qButtons.add(Answer1);
        qButtons.add(Answer2);
        qButtons.add(Answer3);
        qButtons.add(Answer4);
        
        btnLifelines = new ArrayList<JButton>();
        btnLifelines.add(ATA);
        btnLifelines.add(PAF);
        btnLifelines.add(FF);
        
        DefaultTableModel model=new DefaultTableModel()
        {
        @Override
            public boolean isCellEditable(int i, int i1) 
            {
                return false;
            }
        };
        
        jTable1.setModel(model);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setCellSelectionEnabled(false);
        
    }
    
    public void setGame(Game current)
    {
        thisGame = current;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        CardHolder = new javax.swing.JPanel();
        StartScreen = new javax.swing.JPanel();
        javax.swing.JLabel Welcome = new javax.swing.JLabel();
        ViewScoreboard = new javax.swing.JButton();
        Start1 = new javax.swing.JButton();
        StartScreenQuit = new javax.swing.JButton();
        QuestionScreen = new javax.swing.JPanel();
        AnswerButtons = new javax.swing.JPanel();
        Answer1 = new javax.swing.JButton();
        Answer2 = new javax.swing.JButton();
        Answer3 = new javax.swing.JButton();
        Answer4 = new javax.swing.JButton();
        QuestionDisplay = new javax.swing.JPanel();
        lblForPrize = new javax.swing.JLabel();
        pnlLLButtons = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        ATA = new javax.swing.JButton();
        FF = new javax.swing.JButton();
        PAF = new javax.swing.JButton();
        WalkAway = new javax.swing.JButton();
        Scoreboard = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        QuitPlayAgain = new javax.swing.JPanel();
        Quit = new javax.swing.JButton();
        PlayAgain = new javax.swing.JButton();
        SaveScore = new javax.swing.JPanel();
        EndMessage = new javax.swing.JLabel();
        ScoreQuestion = new javax.swing.JPanel();
        lblSaveScore = new javax.swing.JLabel();
        SaveYes = new javax.swing.JButton();
        QuitNoScore = new javax.swing.JButton();
        QuitViewScores = new javax.swing.JButton();
        BacktoMenu = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CardHolder.setLayout(new java.awt.CardLayout());

        StartScreen.setBackground(new java.awt.Color(0, 102, 102));
        StartScreen.setMinimumSize(new java.awt.Dimension(883, 528));
        StartScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Welcome.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 255, 255));
        Welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Welcome.setText("Who Wants to be a Millionaire!");
        Welcome.setToolTipText("");
        StartScreen.add(Welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 880, -1));

        ViewScoreboard.setBackground(new java.awt.Color(204, 0, 204));
        ViewScoreboard.setFont(new java.awt.Font("Input", 0, 14)); // NOI18N
        ViewScoreboard.setForeground(new java.awt.Color(255, 255, 255));
        ViewScoreboard.setText("View High Scores");
        ViewScoreboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewScoreboardActionPerformed(evt);
            }
        });
        StartScreen.add(ViewScoreboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 240, 40));

        Start1.setBackground(new java.awt.Color(0, 204, 0));
        Start1.setFont(new java.awt.Font("Input", 0, 24)); // NOI18N
        Start1.setForeground(new java.awt.Color(255, 255, 255));
        Start1.setText("Start");
        Start1.setMaximumSize(new java.awt.Dimension(133, 32));
        Start1.setMinimumSize(new java.awt.Dimension(133, 32));
        Start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start1ActionPerformed(evt);
            }
        });
        StartScreen.add(Start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 260, 60));

        StartScreenQuit.setBackground(new java.awt.Color(153, 0, 0));
        StartScreenQuit.setFont(new java.awt.Font("Input", 0, 14)); // NOI18N
        StartScreenQuit.setForeground(new java.awt.Color(255, 255, 255));
        StartScreenQuit.setText("Quit");
        StartScreenQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitNoScoreActionPerformed(evt);
            }
        });
        StartScreen.add(StartScreenQuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 470, 240, 40));

        CardHolder.add(StartScreen, "card2");

        QuestionScreen.setBackground(new java.awt.Color(0, 102, 102));

        AnswerButtons.setLayout(new java.awt.GridLayout(2, 2));

        Answer1.setBackground(new java.awt.Color(102, 102, 102));
        Answer1.setFont(new java.awt.Font("Input", 1, 18)); // NOI18N
        Answer1.setForeground(new java.awt.Color(255, 255, 255));
        Answer1.setText("Default Answer 1");
        Answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });
        AnswerButtons.add(Answer1);

        Answer2.setBackground(new java.awt.Color(102, 102, 102));
        Answer2.setFont(new java.awt.Font("Input", 1, 18)); // NOI18N
        Answer2.setForeground(new java.awt.Color(255, 255, 255));
        Answer2.setText("Default Answer 2");
        Answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });
        AnswerButtons.add(Answer2);

        Answer3.setBackground(new java.awt.Color(102, 102, 102));
        Answer3.setFont(new java.awt.Font("Input", 1, 18)); // NOI18N
        Answer3.setForeground(new java.awt.Color(255, 255, 255));
        Answer3.setText("Default Answer 3");
        Answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });
        AnswerButtons.add(Answer3);

        Answer4.setBackground(new java.awt.Color(102, 102, 102));
        Answer4.setFont(new java.awt.Font("Input", 1, 18)); // NOI18N
        Answer4.setForeground(new java.awt.Color(255, 255, 255));
        Answer4.setText("Default Answer 4");
        Answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });
        AnswerButtons.add(Answer4);

        QuestionDisplay.setBackground(new java.awt.Color(0, 102, 102));
        QuestionDisplay.setLayout(new java.awt.GridLayout(2, 1));

        lblForPrize.setBackground(new java.awt.Color(0, 102, 102));
        lblForPrize.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        lblForPrize.setForeground(new java.awt.Color(255, 255, 255));
        lblForPrize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForPrize.setText("For $example");
        QuestionDisplay.add(lblForPrize);

        pnlLLButtons.setBackground(new java.awt.Color(0, 102, 102));
        pnlLLButtons.setLayout(new java.awt.GridLayout(1, 0));

        Question.setBackground(new java.awt.Color(0, 102, 102));
        Question.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Question.setForeground(new java.awt.Color(255, 255, 255));
        Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question.setText("Default Question ONE?");
        pnlLLButtons.add(Question);

        QuestionDisplay.add(pnlLLButtons);

        ATA.setBackground(new java.awt.Color(153, 0, 153));
        ATA.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ATA.setForeground(new java.awt.Color(255, 255, 255));
        ATA.setText("Ask The Audience");
        ATA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifelineActionPerformed(evt);
            }
        });

        FF.setBackground(new java.awt.Color(153, 153, 0));
        FF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        FF.setForeground(new java.awt.Color(255, 255, 255));
        FF.setText("50/50");
        FF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifelineActionPerformed(evt);
            }
        });

        PAF.setBackground(new java.awt.Color(51, 153, 0));
        PAF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        PAF.setForeground(new java.awt.Color(255, 255, 255));
        PAF.setText("Phone a Friend");
        PAF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifelineActionPerformed(evt);
            }
        });

        WalkAway.setBackground(new java.awt.Color(153, 0, 0));
        WalkAway.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        WalkAway.setForeground(new java.awt.Color(255, 255, 255));
        WalkAway.setText("Walk Away");
        WalkAway.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lifelineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuestionScreenLayout = new javax.swing.GroupLayout(QuestionScreen);
        QuestionScreen.setLayout(QuestionScreenLayout);
        QuestionScreenLayout.setHorizontalGroup(
            QuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnswerButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(QuestionScreenLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(ATA)
                .addGap(0, 0, 0)
                .addComponent(FF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PAF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(WalkAway, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuestionScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(QuestionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        QuestionScreenLayout.setVerticalGroup(
            QuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionScreenLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(QuestionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ATA)
                    .addComponent(FF)
                    .addComponent(PAF)
                    .addComponent(WalkAway))
                .addGap(18, 18, 18)
                .addComponent(QuestionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnswerButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CardHolder.add(QuestionScreen, "card3");

        Scoreboard.setBackground(new java.awt.Color(0, 102, 102));
        Scoreboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScore.setFont(new java.awt.Font("Input", 1, 36)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 255, 255));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblScore.setText("Score Board");
        lblScore.setToolTipText("");
        lblScore.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblScore.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblScore.setPreferredSize(new java.awt.Dimension(228, 80));
        Scoreboard.add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 880, -1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(20, 0));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 265));

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setToolTipText("");
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(153, 153, 255));
        jTable1.setMinimumSize(new java.awt.Dimension(45, 0));
        jTable1.setRowMargin(2);
        jTable1.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(2);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        Scoreboard.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 820, 270));

        QuitPlayAgain.setBackground(new java.awt.Color(0, 102, 102));
        QuitPlayAgain.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Quit.setBackground(new java.awt.Color(153, 0, 0));
        Quit.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        Quit.setForeground(new java.awt.Color(255, 255, 255));
        Quit.setText("Quit");
        Quit.setDefaultCapable(false);
        Quit.setFocusable(false);
        Quit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Quit.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        QuitPlayAgain.add(Quit);

        PlayAgain.setBackground(new java.awt.Color(0, 153, 51));
        PlayAgain.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        PlayAgain.setForeground(new java.awt.Color(255, 255, 255));
        PlayAgain.setText("Back to Main Menu");
        PlayAgain.setDefaultCapable(false);
        PlayAgain.setFocusable(false);
        PlayAgain.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PlayAgain.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        PlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayAgainActionPerformed(evt);
            }
        });
        QuitPlayAgain.add(PlayAgain);

        Scoreboard.add(QuitPlayAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 880, 90));

        CardHolder.add(Scoreboard, "card4");

        SaveScore.setBackground(new java.awt.Color(0, 102, 102));
        SaveScore.setForeground(new java.awt.Color(204, 204, 204));
        SaveScore.setLayout(new java.awt.GridLayout(2, 1));

        EndMessage.setBackground(new java.awt.Color(0, 102, 102));
        EndMessage.setFont(new java.awt.Font("Input", 1, 18)); // NOI18N
        EndMessage.setForeground(new java.awt.Color(255, 255, 255));
        EndMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EndMessage.setText("end message here");
        SaveScore.add(EndMessage);

        ScoreQuestion.setBackground(new java.awt.Color(0, 102, 102));
        ScoreQuestion.setForeground(new java.awt.Color(204, 204, 204));
        ScoreQuestion.setLayout(new java.awt.GridBagLayout());

        lblSaveScore.setFont(new java.awt.Font("Input", 1, 24)); // NOI18N
        lblSaveScore.setForeground(new java.awt.Color(255, 255, 255));
        lblSaveScore.setText("Save your score?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        ScoreQuestion.add(lblSaveScore, gridBagConstraints);

        SaveYes.setBackground(new java.awt.Color(0, 153, 51));
        SaveYes.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        SaveYes.setForeground(new java.awt.Color(255, 255, 255));
        SaveYes.setText("Yes");
        SaveYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveYesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        ScoreQuestion.add(SaveYes, gridBagConstraints);

        QuitNoScore.setBackground(new java.awt.Color(153, 0, 0));
        QuitNoScore.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        QuitNoScore.setForeground(new java.awt.Color(255, 255, 255));
        QuitNoScore.setText("No, just quit");
        QuitNoScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitNoScoreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        ScoreQuestion.add(QuitNoScore, gridBagConstraints);

        QuitViewScores.setBackground(new java.awt.Color(102, 51, 255));
        QuitViewScores.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        QuitViewScores.setForeground(new java.awt.Color(255, 255, 255));
        QuitViewScores.setText("No, view score board");
        QuitViewScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitViewScoresActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 4, 0);
        ScoreQuestion.add(QuitViewScores, gridBagConstraints);

        BacktoMenu.setBackground(new java.awt.Color(204, 102, 0));
        BacktoMenu.setFont(new java.awt.Font("Input", 0, 12)); // NOI18N
        BacktoMenu.setForeground(new java.awt.Color(255, 255, 255));
        BacktoMenu.setText("Back to Main Menu");
        BacktoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        ScoreQuestion.add(BacktoMenu, gridBagConstraints);

        SaveScore.add(ScoreQuestion);

        CardHolder.add(SaveScore, "card5");

        add(CardHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 882, 527));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        
    }//GEN-LAST:event_exitForm

    private void ViewScoreboardActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ViewScoreboardActionPerformed
    {//GEN-HEADEREND:event_ViewScoreboardActionPerformed
        
    }//GEN-LAST:event_ViewScoreboardActionPerformed

    private void Start1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Start1ActionPerformed
    {//GEN-HEADEREND:event_Start1ActionPerformed

          
    }//GEN-LAST:event_Start1ActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitActionPerformed
    {//GEN-HEADEREND:event_QuitActionPerformed
        
    }//GEN-LAST:event_QuitActionPerformed

    private void btnAnswerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAnswerActionPerformed
    {//GEN-HEADEREND:event_btnAnswerActionPerformed
        
    }//GEN-LAST:event_btnAnswerActionPerformed

    private void lifelineActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lifelineActionPerformed
    {//GEN-HEADEREND:event_lifelineActionPerformed
        
    }//GEN-LAST:event_lifelineActionPerformed

    private void QuitViewScoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitViewScoresActionPerformed
    {//GEN-HEADEREND:event_QuitViewScoresActionPerformed
        
    }//GEN-LAST:event_QuitViewScoresActionPerformed

    private void QuitNoScoreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_QuitNoScoreActionPerformed
    {//GEN-HEADEREND:event_QuitNoScoreActionPerformed
        
    }//GEN-LAST:event_QuitNoScoreActionPerformed

    private void PlayAgainActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PlayAgainActionPerformed
    {//GEN-HEADEREND:event_PlayAgainActionPerformed
        
    }//GEN-LAST:event_PlayAgainActionPerformed

    private void BacktoMenuActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BacktoMenuActionPerformed
    {//GEN-HEADEREND:event_BacktoMenuActionPerformed
        
    }//GEN-LAST:event_BacktoMenuActionPerformed

    private void SaveYesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SaveYesActionPerformed
    {//GEN-HEADEREND:event_SaveYesActionPerformed
        
    }//GEN-LAST:event_SaveYesActionPerformed

    public void changeCard(String cardName)
    {
        
    }
   
    public void setQuestionText(String text)
    {
        
    }
    
    public void setPrize(String prize)
    {
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ATA;
    private javax.swing.JButton Answer1;
    private javax.swing.JButton Answer2;
    private javax.swing.JButton Answer3;
    private javax.swing.JButton Answer4;
    private javax.swing.JPanel AnswerButtons;
    private javax.swing.JButton BacktoMenu;
    private javax.swing.JPanel CardHolder;
    public javax.swing.JLabel EndMessage;
    private javax.swing.JButton FF;
    private javax.swing.JButton PAF;
    private javax.swing.JButton PlayAgain;
    private javax.swing.JLabel Question;
    private javax.swing.JPanel QuestionDisplay;
    private javax.swing.JPanel QuestionScreen;
    private javax.swing.JButton Quit;
    private javax.swing.JButton QuitNoScore;
    private javax.swing.JPanel QuitPlayAgain;
    private javax.swing.JButton QuitViewScores;
    private javax.swing.JPanel SaveScore;
    private javax.swing.JButton SaveYes;
    private javax.swing.JPanel ScoreQuestion;
    private javax.swing.JPanel Scoreboard;
    private javax.swing.JButton Start1;
    private javax.swing.JPanel StartScreen;
    private javax.swing.JButton StartScreenQuit;
    private javax.swing.JButton ViewScoreboard;
    private javax.swing.JButton WalkAway;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JLabel lblForPrize;
    private javax.swing.JLabel lblSaveScore;
    private javax.swing.JLabel lblScore;
    private javax.swing.JPanel pnlLLButtons;
    // End of variables declaration//GEN-END:variables
}
